/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import controlador.PlanillaFacade;
import modelo.Area;
import modelo.Empleado;
import java.util.ArrayList;
import java.util.List;
import util.Mensajes;
import util.ValidadorEmpleado;

/*
 * @author User
 */
public class FrmEmpleado extends javax.swing.JPanel {

    private final PlanillaFacade planillaFacade;
    private final List<Area> areas = new ArrayList<>();

    public FrmEmpleado() {
        this(new PlanillaFacade(), null);
    }

    public FrmEmpleado(PlanillaFacade facade, Empleado empleado) {
        this.planillaFacade = facade;
        initComponents();
        txtResultado.setEditable(false);
        cargarCombos();
        if (empleado != null) {
            cargarEmpleado(empleado);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtHorasTrabajadas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBonificacion = new javax.swing.JTextField();
        txtTarifaPorHora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboHijos = new javax.swing.JComboBox<>();
        cboArea = new javax.swing.JComboBox<>();
        cboDias = new javax.swing.JComboBox<>();
        txtDni = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Numero de hijos:");

        jLabel3.setText("Dias asistidos:");

        jLabel4.setText("Horas trabajadas:");

        jLabel5.setText("Area:");

        jLabel6.setText("Bonificacion");

        jLabel7.setText("Tarifa por hora:");

        cboHijos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "mas de 4" }));

        cboArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("DNI:");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("REGISTRO EMPLEADOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(47, 47, 47)
                .addComponent(btnModificar)
                .addGap(50, 50, 50)
                .addComponent(btnActualizar)
                .addGap(49, 49, 49)
                .addComponent(btnEliminar)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtBonificacion, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTarifaPorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtHorasTrabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cboHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3))
                            .addGap(109, 109, 109))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBonificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTarifaPorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtHorasTrabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModificar)
                        .addComponent(btnActualizar)
                        .addComponent(btnEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            Empleado empleado = crearEmpleadoDesdeFormulario();
            planillaFacade.registrarEmpleado(empleado);
            mostrarVistaPrevia(empleado);
            Mensajes.informacion(this, "Empleado registrado correctamente.");

        } catch (RuntimeException e) {
            Mensajes.error(this, e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            Empleado empleado = planillaFacade.buscarEmpleadoPorDni(ValidadorEmpleado.dni(txtDni.getText()));
            if (empleado == null) {
                throw new IllegalArgumentException("No se encontró un empleado con ese DNI.");
            }
            cargarEmpleado(empleado);
            Mensajes.informacion(this, "Datos cargados. Modifique los campos y presione Actualizar.");
        } catch (RuntimeException e) {
            Mensajes.error(this, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            Empleado empleado = crearEmpleadoDesdeFormulario();
            planillaFacade.actualizarEmpleado(empleado);
            mostrarVistaPrevia(empleado);
            Mensajes.informacion(this, "Empleado actualizado correctamente.");
        } catch (RuntimeException e) {
            Mensajes.error(this, e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            String dni = ValidadorEmpleado.dni(txtDni.getText());
            if (Mensajes.confirmarEliminacion(this)) {
                planillaFacade.eliminarEmpleado(dni);
                limpiarFormulario();
                Mensajes.informacion(this, "Empleado eliminado correctamente.");
            }
        } catch (RuntimeException e) {
            Mensajes.error(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cargarCombos() {
        cboDias.removeAllItems();
        for (int dia = 0; dia <= 30; dia++) {
            cboDias.addItem(String.valueOf(dia));
        }
        cboArea.removeAllItems();
        try {
            areas.clear();
            areas.addAll(planillaFacade.listarAreas());
            for (Area area : areas) {
                cboArea.addItem(area.getNombre());
            }
        } catch (RuntimeException e) {
            Mensajes.error(this, e.getMessage());
        }
    }

    private Empleado crearEmpleadoDesdeFormulario() {
        if (cboArea.getSelectedIndex() < 0) {
            throw new IllegalArgumentException("Seleccione un área.");
        }
        int hijos = cboHijos.getSelectedIndex() == 5 ? 5 : Integer.parseInt((String) cboHijos.getSelectedItem());
        return new Empleado.Builder()
                .dni(ValidadorEmpleado.dni(txtDni.getText()))
                .nombre(ValidadorEmpleado.textoObligatorio(txtNombre.getText(), "el nombre"))
                .horasTrabajadas(ValidadorEmpleado.enteroNoNegativo(txtHorasTrabajadas.getText(), "Las horas trabajadas"))
                .tarifaHora(ValidadorEmpleado.montoNoNegativo(txtTarifaPorHora.getText(), "La tarifa por hora"))
                .bonificacion(ValidadorEmpleado.montoNoNegativo(txtBonificacion.getText(), "La bonificación"))
                .diasAsistidos(Integer.parseInt((String) cboDias.getSelectedItem()))
                .numeroHijos(hijos)
                .area(areas.get(cboArea.getSelectedIndex()))
                .build();
    }

    private void cargarEmpleado(Empleado empleado) {
        txtDni.setText(empleado.getDni());
        txtNombre.setText(empleado.getNombre());
        txtHorasTrabajadas.setText(String.valueOf(empleado.getHorasTrabajadas()));
        txtTarifaPorHora.setText(empleado.getTarifaHora().toPlainString());
        txtBonificacion.setText(empleado.getBonificacion().toPlainString());
        cboDias.setSelectedItem(String.valueOf(empleado.getDiasAsistidos()));
        cboHijos.setSelectedIndex(Math.min(empleado.getNumeroHijos(), 5));
        for (int i = 0; i < areas.size(); i++) {
            if (areas.get(i).getIdArea().equals(empleado.getArea().getIdArea())) {
                cboArea.setSelectedIndex(i);
                break;
            }
        }
        mostrarVistaPrevia(empleado);
    }

    private void mostrarVistaPrevia(Empleado empleado) {
        txtResultado.setText(planillaFacade.generarBoletaTexto(empleado, "Detallado"));
    }

    private void limpiarFormulario() {
        txtDni.setText("");
        txtNombre.setText("");
        txtHorasTrabajadas.setText("");
        txtTarifaPorHora.setText("");
        txtBonificacion.setText("");
        cboHijos.setSelectedIndex(0);
        cboDias.setSelectedIndex(30);
        if (cboArea.getItemCount() > 0) {
            cboArea.setSelectedIndex(0);
        }
        txtResultado.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cboArea;
    private javax.swing.JComboBox<String> cboDias;
    private javax.swing.JComboBox<String> cboHijos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBonificacion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtHorasTrabajadas;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtTarifaPorHora;
    // End of variables declaration//GEN-END:variables
}
