/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import controlador.EmpleadoControlador;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.function.Consumer;
import javax.swing.table.DefaultTableModel;
import modelo.Empleado;
import util.Mensajes;
/**
 *
 * @author User
 */
public class FrmListaEmpleados extends javax.swing.JPanel {
    private final EmpleadoControlador empleadoControlador;
    private final Consumer<Empleado> alModificar;
    private final Consumer<String> alGenerarBoleta;
    /**
     * Creates new form FrmListaEmpleados
     */
    public FrmListaEmpleados() {
        this(new EmpleadoControlador(), null, null);
    }

    public FrmListaEmpleados(EmpleadoControlador controlador, Consumer<Empleado> alModificar, Consumer<String> alGenerarBoleta) {
        this.empleadoControlador = controlador;
        this.alModificar = alModificar;
        this.alGenerarBoleta = alGenerarBoleta;
        initComponents();
        configurarTabla();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegistro = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtBuscarDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGenerarBoleta = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tableRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Area", "Hijos", "Dias", "Neto"
            }
        ));
        jScrollPane1.setViewportView(tableRegistro);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("LISTA DE EMPLEADOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel2.setText("Buscar por DNI:");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnGenerarBoleta.setText("Generar Boleta");
        btnGenerarBoleta.addActionListener(this::btnGenerarBoletaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar)
                                .addGap(26, 26, 26)
                                .addComponent(btnEliminar)
                                .addGap(30, 30, 30)
                                .addComponent(btnGenerarBoleta)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGenerarBoleta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            Empleado empleado = empleadoSeleccionado();
            if (alModificar != null) alModificar.accept(empleado);
            else Mensajes.informacion(this, "Abra este panel desde el menú principal para modificar el empleado.");
        } catch (RuntimeException e) {
            Mensajes.error(this, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            Empleado empleado = empleadoSeleccionado();
            if (Mensajes.confirmarEliminacion(this)) {
                empleadoControlador.eliminar(empleado.getDni());
                cargarTabla();
                Mensajes.informacion(this, "Empleado eliminado correctamente.");
            }
        } catch (RuntimeException e) {
            Mensajes.error(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGenerarBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarBoletaActionPerformed
        try {
            Empleado empleado = empleadoSeleccionado();
            if (alGenerarBoleta != null) alGenerarBoleta.accept(empleado.getDni());
            else Mensajes.informacion(this, "Abra este panel desde el menú principal para generar la boleta.");
        } catch (RuntimeException e) {
            Mensajes.error(this, e.getMessage());
        }
    }//GEN-LAST:event_btnGenerarBoletaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            String dni = util.ValidadorEmpleado.dni(txtBuscarDni.getText());
            Empleado empleado = empleadoControlador.buscarPorDni(dni);
            if (empleado == null) { Mensajes.informacion(this, "Empleado no encontrado."); return; }
            DefaultTableModel modelo = (DefaultTableModel) tableRegistro.getModel();
            modelo.setRowCount(0); agregarFila(modelo, empleado);
        } catch (RuntimeException e) {
            Mensajes.error(this, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void configurarTabla() {
        tableRegistro.setModel(new DefaultTableModel(new Object[][]{}, new String[]{"DNI", "Nombre", "Área", "Hijos", "Días", "Neto"}) {
            @Override public boolean isCellEditable(int fila, int columna) { return false; }
        });
    }

    private void cargarTabla() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tableRegistro.getModel(); modelo.setRowCount(0);
            for (Empleado empleado : empleadoControlador.listar()) agregarFila(modelo, empleado);
        } catch (RuntimeException e) { Mensajes.error(this, e.getMessage()); }
    }

    private void agregarFila(DefaultTableModel modelo, Empleado empleado) {
        String neto = NumberFormat.getCurrencyInstance(new Locale("es", "PE")).format(empleado.calcularSueldoNeto());
        modelo.addRow(new Object[]{empleado.getDni(), empleado.getNombre(), empleado.getArea().getNombre(), empleado.getNumeroHijos(), empleado.getDiasAsistidos(), neto});
    }

    private Empleado empleadoSeleccionado() {
        int fila = tableRegistro.getSelectedRow();
        if (fila < 0) throw new IllegalArgumentException("Seleccione un empleado en la tabla.");
        Empleado empleado = empleadoControlador.buscarPorDni(String.valueOf(tableRegistro.getValueAt(fila, 0)));
        if (empleado == null) throw new IllegalArgumentException("El empleado ya no existe.");
        return empleado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerarBoleta;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRegistro;
    private javax.swing.JTextField txtBuscarDni;
    // End of variables declaration//GEN-END:variables
}
