/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import controlador.EmpleadoControlador;
import java.awt.BorderLayout;
import javax.swing.*;

/**
 *
 * @author User
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());
    private final EmpleadoControlador empleadoControlador = new EmpleadoControlador();

    /**
     * Creates new form NewJFrame
     */
    public FrmPrincipal() {
        initComponents();
    }

    private void mostrarPanel(JPanel vista) {
        vista.setSize(pnlContenido.getWidth(), pnlContenido.getHeight());
        vista.setLocation(0, 0);

        pnlContenido.removeAll();
        pnlContenido.add(vista, java.awt.BorderLayout.CENTER);
        pnlContenido.revalidate();
        pnlContenido.repaint();
    }

    private void abrirEmpleado(modelo.Empleado empleado) {
        mostrarPanel(new FrmEmpleado(empleadoControlador, empleado, null));
    }

    private void abrirBoleta(String dni) {
        FrmBoleta boleta = new FrmBoleta(empleadoControlador);
        if (dni != null) {
            boleta.seleccionarEmpleado(dni);
        }
        mostrarPanel(boleta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        btnGenerarBoletas = new javax.swing.JButton();
        btnListarEmpleados = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnAsistenciaPerfecta = new javax.swing.JButton();
        btnRegistrarEmpleado = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(0, 0, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(210, 576));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerarBoletas.setText("Generar Boletas");
        btnGenerarBoletas.addActionListener(this::btnGenerarBoletasActionPerformed);
        pnlPrincipal.add(btnGenerarBoletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, 40));

        btnListarEmpleados.setText("Listar empleados");
        btnListarEmpleados.addActionListener(this::btnListarEmpleadosActionPerformed);
        pnlPrincipal.add(btnListarEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, 40));

        btnCerrar.setBackground(new java.awt.Color(255, 51, 51));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);
        pnlPrincipal.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 70, 30));

        btnAsistenciaPerfecta.setText("Asistencia Perfecta");
        btnAsistenciaPerfecta.addActionListener(this::btnAsistenciaPerfectaActionPerformed);
        pnlPrincipal.add(btnAsistenciaPerfecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, 40));

        btnRegistrarEmpleado.setText("Registrar empleado");
        btnRegistrarEmpleado.addActionListener(this::btnRegistrarEmpleadoActionPerformed);
        pnlPrincipal.add(btnRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 40));

        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.WEST);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(51, 0, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("GESTION LABORAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel1)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pnlContenido.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEmpleadoActionPerformed
        abrirEmpleado(null);
    }//GEN-LAST:event_btnRegistrarEmpleadoActionPerformed

    private void btnGenerarBoletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarBoletasActionPerformed
        FrmBoleta f = new FrmBoleta(empleadoControlador);
        // Quitamos la condición del DNI porque al presionar el menú lateral 
        // se asume que vas a generar una boleta nueva buscando al empleado desde cero
        mostrarPanel(f);
    }//GEN-LAST:event_btnGenerarBoletasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnListarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarEmpleadosActionPerformed
        // Cargamos la lista de empleados pasándole los métodos de redirección
        mostrarPanel(new FrmListaEmpleados(empleadoControlador, this::abrirEmpleado, this::abrirBoleta));
    }//GEN-LAST:event_btnListarEmpleadosActionPerformed

    private void btnAsistenciaPerfectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciaPerfectaActionPerformed
        mostrarPanel(new FrmAsistenciaPerfecta(empleadoControlador));
    }//GEN-LAST:event_btnAsistenciaPerfectaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsistenciaPerfecta;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGenerarBoletas;
    private javax.swing.JButton btnListarEmpleados;
    private javax.swing.JButton btnRegistrarEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
