/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sueldos_empleados;

import Datos.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
  

    public class Menu extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
        private EmpleadoService service;

        /**
         * Creates new form NewJFrame
         */
        public Menu() {
            initComponents();
            service = new EmpleadoService(20);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAbreJFrameRegistrarTrabajador = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setForeground(new java.awt.Color(51, 0, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("GESTION LABORAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        btnAbreJFrameRegistrarTrabajador.setText("Registrar Trabajador");
        btnAbreJFrameRegistrarTrabajador.addActionListener(this::btnAbreJFrameRegistrarTrabajadorActionPerformed);

        jButton2.setText("Generar Boletas");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Buscar Trabajador");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Listar Trabajadores");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Asistencia Perfecta");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAbreJFrameRegistrarTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAbreJFrameRegistrarTrabajador)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbreJFrameRegistrarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbreJFrameRegistrarTrabajadorActionPerformed
        RegistroTrabajador RT = new RegistroTrabajador(service);
        RT.setVisible(true);
    }//GEN-LAST:event_btnAbreJFrameRegistrarTrabajadorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Empleado[] empleados = service.getEmpleados();

        int total = service.getContador();

        if (total == 0) {

            JOptionPane.showMessageDialog(this, "No hay empleados registrados");

            return;
        }

        String resultado = "";

        for (int i = 0; i < total; i++) {

            Empleado emp = empleados[i];

            double sueldoBruto = emp.getHorasTrabajadas() * emp.getTarifaHora();

            double descuento = (7 - emp.getDiasAsistidos()) * 10;

            double sueldoNeto = sueldoBruto + emp.getBonificacion() - descuento;

            resultado
                    += "===== BOLETA DE PAGO =====\n"
                    + "Nombre: " + emp.getNombre() + "\n"
                    + "DNI: " + emp.getDni() + "\n"
                    + "Horas trabajadas: "
                    + emp.getHorasTrabajadas() + "\n"
                    + "Tarifa por hora: S/ "
                    + emp.getTarifaHora() + "\n"
                    + "Bonificación: S/ "
                    + emp.getBonificacion() + "\n"
                    + "Sueldo Bruto: S/ "
                    + sueldoBruto + "\n"
                    + "Descuento: S/ "
                    + descuento + "\n"
                    + "Sueldo Neto: S/ "
                    + sueldoNeto + "\n\n";
        }

        JOptionPane.showMessageDialog(
                this,
                resultado
        );
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String dniBuscar = JOptionPane.showInputDialog(
                this,
                "Ingrese DNI del trabajador"
        );

        if (dniBuscar == null || dniBuscar.trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Debe ingresar un DNI"
            );

            return;
        }

        Empleado[] empleados = service.getEmpleados();

        int total = service.getContador();

        boolean encontrado = false;

        for (int i = 0; i < total; i++) {
            Empleado emp = empleados[i];

            if (emp.getDni().equals(dniBuscar)) {

                double sueldoBruto = emp.getHorasTrabajadas() * emp.getTarifaHora();

                double descuento = (7 - emp.getDiasAsistidos()) * 10;

                double sueldoNeto = sueldoBruto + emp.getBonificacion() - descuento;

                // MOSTRAR RESULTADO
                JOptionPane.showMessageDialog(this,
                        "===== TRABAJADOR =====\n\n"
                        + "Nombre: "
                        + emp.getNombre() + "\n"
                        + "DNI: "
                        + emp.getDni() + "\n"
                        + "Horas trabajadas: "
                        + emp.getHorasTrabajadas() + "\n"
                        + "Sueldo Neto: S/ "
                        + sueldoNeto
                );

                encontrado = true;

                break;
            }
        }

        // SI NO EXISTE
        if (!encontrado) {

            JOptionPane.showMessageDialog(this, "Trabajador no encontrado");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(this, service.listarTrabajadores()
        );
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int total = service.contarAsistenciaPerfecta();

        if (total == 0) {

            JOptionPane.showMessageDialog(this,"No hay empleados con asistencia perfecta");

        } else {
            JOptionPane.showMessageDialog(this,
                    "===== ASISTENCIA PERFECTA =====\n\n"
                    + service.obtenerAsistenciaPerfecta()
                    + "\nTotal: " + total
            );
        }   
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbreJFrameRegistrarTrabajador;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
